/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import proyecto2so.IA;
import proyecto2so.Admin;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import proyecto2so.Personaje;

/**
 *
 * @author SebasBD
 */
public class Interfaz extends javax.swing.JFrame {
    public static DefaultListModel<String> modeloListaGanadores;
    /**
     * Creates new form MainInterfaz
     */
    public Interfaz() {
        initComponents();
        coronaLabelUSM.setVisible(false);
        coronaLabelLLDA.setVisible(false);
        empateLabel.setVisible(false);
        cancelLabel.setVisible(false);
        modeloListaGanadores = new DefaultListModel<>();
        ListaGanadores.setModel(modeloListaGanadores);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Colas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ColasUSM1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ColasUSM2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ColasUSM3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ColasUSM4 = new javax.swing.JLabel();
        Colas2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ColasLLDA1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ColasLLDA2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        ColasLLDA3 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ColasLLDA4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cancelLabel = new javax.swing.JLabel();
        PuntosUnicosLLDA = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LLDAIMG = new javax.swing.JLabel();
        USMIMG = new javax.swing.JLabel();
        PuntosUnicosUSM = new javax.swing.JLabel();
        nombreUSM = new javax.swing.JLabel();
        nombreLLDA = new javax.swing.JLabel();
        PuntosUSM1 = new javax.swing.JLabel();
        PuntosLLDA1 = new javax.swing.JLabel();
        coronaLabelUSM = new javax.swing.JLabel();
        coronaLabelLLDA = new javax.swing.JLabel();
        EstadoIA = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        empateLabel = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        ListaGanadores = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        SliderAITimer = new javax.swing.JSlider();
        jPanel4 = new javax.swing.JPanel();
        ganadoresLLDA = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ganadoresUSM = new javax.swing.JLabel();
        LLDAFondo = new javax.swing.JLabel();
        USMFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Avatar: La Leyenda de Aang");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 80, 540, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel2.setText("FIGHT!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 190, 80));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Un Show Mas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 490, 80));

        Colas.setBackground(new java.awt.Color(153, 153, 255));
        Colas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        Colas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ColasUSM1.setBackground(new java.awt.Color(0, 0, 255));
        ColasUSM1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasUSM1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(ColasUSM1);

        Colas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 270, 60));

        ColasUSM2.setBackground(new java.awt.Color(0, 0, 255));
        ColasUSM2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasUSM2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane3.setViewportView(ColasUSM2);

        Colas.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 270, 60));

        ColasUSM3.setBackground(new java.awt.Color(0, 0, 255));
        ColasUSM3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasUSM3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane4.setViewportView(ColasUSM3);

        Colas.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 270, 60));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Colas de prioridad");
        Colas.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 40));

        ColasUSM4.setBackground(new java.awt.Color(0, 0, 255));
        ColasUSM4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasUSM4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane5.setViewportView(ColasUSM4);

        Colas.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 270, 60));

        jPanel1.add(Colas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 290, 360));

        Colas2.setBackground(new java.awt.Color(255, 204, 102));
        Colas2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        Colas2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ColasLLDA1.setBackground(new java.awt.Color(0, 0, 0));
        ColasLLDA1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasLLDA1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane2.setViewportView(ColasLLDA1);

        Colas2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 270, 60));

        ColasLLDA2.setBackground(new java.awt.Color(0, 0, 0));
        ColasLLDA2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasLLDA2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane6.setViewportView(ColasLLDA2);

        Colas2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 270, 60));

        ColasLLDA3.setBackground(new java.awt.Color(0, 0, 0));
        ColasLLDA3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasLLDA3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane7.setViewportView(ColasLLDA3);

        Colas2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 270, 60));

        ColasLLDA4.setBackground(new java.awt.Color(0, 0, 0));
        ColasLLDA4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasLLDA4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane8.setViewportView(ColasLLDA4);

        Colas2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 270, 60));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Colas de prioridad");
        Colas2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 40));

        jPanel1.add(Colas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 200, 290, 370));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Cancel.png"))); // NOI18N
        jPanel2.add(cancelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 420, 150));

        PuntosUnicosLLDA.setBackground(new java.awt.Color(255, 255, 255));
        PuntosUnicosLLDA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PuntosUnicosLLDA.setForeground(new java.awt.Color(255, 255, 255));
        PuntosUnicosLLDA.setText("0");
        jPanel2.add(PuntosUnicosLLDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 50, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/VS.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 80, 100));

        LLDAIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/question.jpg"))); // NOI18N
        jPanel2.add(LLDAIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 150, 150));

        USMIMG.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        USMIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/question.jpg"))); // NOI18N
        jPanel2.add(USMIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 150));

        PuntosUnicosUSM.setBackground(new java.awt.Color(255, 255, 255));
        PuntosUnicosUSM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PuntosUnicosUSM.setForeground(new java.awt.Color(255, 255, 255));
        PuntosUnicosUSM.setText("0");
        jPanel2.add(PuntosUnicosUSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 50, 30));

        nombreUSM.setBackground(new java.awt.Color(255, 255, 255));
        nombreUSM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreUSM.setForeground(new java.awt.Color(255, 255, 255));
        nombreUSM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreUSM.setText("Nombre");
        jPanel2.add(nombreUSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 170, 30));

        nombreLLDA.setBackground(new java.awt.Color(255, 255, 255));
        nombreLLDA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreLLDA.setForeground(new java.awt.Color(255, 255, 255));
        nombreLLDA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreLLDA.setText("Nombre");
        jPanel2.add(nombreLLDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 170, 30));

        PuntosUSM1.setBackground(new java.awt.Color(255, 255, 255));
        PuntosUSM1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PuntosUSM1.setForeground(new java.awt.Color(255, 255, 255));
        PuntosUSM1.setText("Puntos:");
        jPanel2.add(PuntosUSM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 60, 30));

        PuntosLLDA1.setBackground(new java.awt.Color(255, 255, 255));
        PuntosLLDA1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PuntosLLDA1.setForeground(new java.awt.Color(255, 255, 255));
        PuntosLLDA1.setText("Puntos:");
        jPanel2.add(PuntosLLDA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 70, 30));

        coronaLabelUSM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coronaLabelUSM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/crown.png"))); // NOI18N
        jPanel2.add(coronaLabelUSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 80, 60));

        coronaLabelLLDA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coronaLabelLLDA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/crown.png"))); // NOI18N
        jPanel2.add(coronaLabelLLDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 80, 60));

        EstadoIA.setBackground(new java.awt.Color(255, 255, 255));
        EstadoIA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EstadoIA.setForeground(new java.awt.Color(255, 255, 255));
        EstadoIA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EstadoIA.setText("CREANDO COLAS");
        jPanel2.add(EstadoIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 150, 50));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Timer (seg)");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, -1));

        empateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empateLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bruja.jpg"))); // NOI18N
        jPanel2.add(empateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 80, 80));

        jScrollPane9.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ListaGanadores.setBackground(new java.awt.Color(0, 0, 0));
        ListaGanadores.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ListaGanadores.setForeground(new java.awt.Color(255, 255, 255));
        ListaGanadores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ganador 1", "Ganador 2", "Ganador 3", "Ganador 4", "Ganadro 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(ListaGanadores);

        jPanel2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 290, 80));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GANADORES =");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        SliderAITimer.setBackground(new java.awt.Color(0, 0, 0));
        SliderAITimer.setForeground(new java.awt.Color(255, 0, 0));
        SliderAITimer.setMajorTickSpacing(1);
        SliderAITimer.setMaximum(10);
        SliderAITimer.setMinimum(1);
        SliderAITimer.setPaintLabels(true);
        SliderAITimer.setPaintTicks(true);
        SliderAITimer.setSnapToTicks(true);
        SliderAITimer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SliderAITimer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderAITimerStateChanged(evt);
            }
        });
        jPanel2.add(SliderAITimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 440, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 460, 580));

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ganadoresLLDA.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        ganadoresLLDA.setForeground(new java.awt.Color(255, 255, 255));
        ganadoresLLDA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ganadoresLLDA.setText("0");
        ganadoresLLDA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel4.add(ganadoresLLDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 70));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 110, 70));

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ganadoresUSM.setBackground(new java.awt.Color(153, 153, 255));
        ganadoresUSM.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        ganadoresUSM.setForeground(new java.awt.Color(255, 255, 255));
        ganadoresUSM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ganadoresUSM.setText("0");
        ganadoresUSM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel3.add(ganadoresUSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 110, 70));

        LLDAFondo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LLDAFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/featuredImage.jpg"))); // NOI18N
        LLDAFondo.setToolTipText("");
        jPanel1.add(LLDAFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 760, 780));

        USMFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Mordecai-and-Rigby-regular-show-30642146-1280-1024.jpg"))); // NOI18N
        jPanel1.add(USMFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 780));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SliderAITimerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderAITimerStateChanged
        IA.tiempo = SliderAITimer.getValue();
    }//GEN-LAST:event_SliderAITimerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });

        // Crear instancias de las clases necesarias
        Admin admin = new Admin();
        IA ia = new IA();

        // Inicializar personajes y colocarlos en las colas
        admin.inicializarPersonajes();

        // Simular rondas de la IA
        for (int round = 1; round <= 1000; round++) { // Ejemplo: 1000 rondas
            System.out.println("\n--- Ronda " + round + " ---");

            // Mostrar las colas antes de la ronda
            admin.printColas();

            // Seleccionar personajes para el combate desde las colas
            Personaje[] personajesParaPelea = admin.seleccionarPersonajesParaPelear();
            Personaje USMPersonaje = personajesParaPelea[0];
            Personaje LLDAPersonaje = personajesParaPelea[1];
       
            if (USMPersonaje != null && LLDAPersonaje != null) {
                System.out.println("Inicia el combate: " + USMPersonaje.getNombre() + " vs " + LLDAPersonaje.getNombre());
            }
            // Mostrar las colas en la interfaz
            admin.actualizarColasEnInterfaz();

            // Procesar la batalla en la IA
            ia.procesarPelea(USMPersonaje, LLDAPersonaje);

            // Actualizar las colas después de la ronda
        }

        // Mostrar las colas al final de la simulación
        System.out.println("\n--- Colas finales ---");
        admin.printColas();
        admin.actualizarColasEnInterfaz();
    }

    public static void setDefStats() {
        if (USMIMG != null && LLDAIMG != null) {
            USMIMG.setIcon(new ImageIcon("src\\imgs\\question.jpg"));
            LLDAIMG.setIcon(new ImageIcon("src\\imgs\\question.jpg"));
            nombreUSM.setText("Buscando oponente");
            nombreLLDA.setText("Buscando oponente");
            PuntosUnicosUSM.setText("0");
            PuntosUnicosLLDA.setText("0");

        } else {
            System.out.println("USMIMG o LLDAIMG es null. Asegúrate de que estén inicializados correctamente.");
        }
    }

    public static void setUSMIcon(String name, int power) {
        USMIMG.setIcon(new ImageIcon("src\\imgs\\" + name + ".jpg"));
        nombreUSM.setText(name);
        PuntosUnicosUSM.setText(Integer.toString(power));
    }

    public static void setLLDAIcon(String name, int power) {
        LLDAIMG.setIcon(new ImageIcon("src\\imgs\\" + name + ".jpg"));
        nombreLLDA.setText(name);
        PuntosUnicosLLDA.setText(Integer.toString(power));
    }

    public static void marcadorUSM(int puntaje) {
        ganadoresUSM.setText(Integer.toString(puntaje));
    }

    public static void marcadorLLDA(int puntaje) {
        ganadoresLLDA.setText(Integer.toString(puntaje));
    }

    public static JLabel getGanadoresLLDA() {
        return ganadoresLLDA;
    }

    public static void setGanadoresLLDA(JLabel ganadoresLLDA) {
        Interfaz.ganadoresLLDA = ganadoresLLDA;
    }

    public static JLabel getGanadoresUSM() {
        return ganadoresUSM;
    }

    public static void setGanadoresUSM(JLabel ganadoresUSM) {
        Interfaz.ganadoresUSM = ganadoresUSM;
    }

    // Método para colocar la corona sobre la imagen del personaje ganador
    public static void setCoronaPosicionUSM(JLabel characterImage) {
        coronaLabelUSM.setVisible(true);
    }

    public static void setCoronaPosicionLLDA(JLabel characterImage) {
        coronaLabelLLDA.setVisible(true);
    }

    public static void setEmpateVisible() {
        empateLabel.setVisible(true);
    }

    public static void setCancelVisible() {
        cancelLabel.setVisible(true);
    }

    public static JLabel getCancelLabel() {
        return cancelLabel;
    }

    public static void setCancelLabel(JLabel cancelLabel) {
        Interfaz.cancelLabel = cancelLabel;
    }

    public static JLabel getEmpateLabel() {
        return empateLabel;
    }

    public static void setEmpateLabel(JLabel empateLabel) {
        Interfaz.empateLabel = empateLabel;
    }

    public static void setNombreZ(String name) {
        nombreUSM.setText(name);
    }

    public static void setNombreSF(String name) {
        nombreLLDA.setText(name);
    }

    public static JLabel getColasUSM(int index) {
        switch (index) {
            case 1:
                return ColasUSM1;
            case 2:
                return ColasUSM2;
            case 3:
                return ColasUSM3;
            case 4:
                return ColasUSM4;
            default:
                return null;
        }
    }

    public static JLabel getColasLLDA(int index) {
        switch (index) {
            case 1:
                return ColasLLDA1;
            case 2:
                return ColasLLDA2;
            case 3:
                return ColasLLDA3;
            case 4:
                return ColasLLDA4;
            default:
                return null;
        }
    }

    public static JLabel getLLDAIMG() {
        return LLDAIMG;
    }

    public static void setLLDAIMG(JLabel LLDAIMG) {
        Interfaz.LLDAIMG = LLDAIMG;
    }

    public static JLabel getUSMIMG() {
        return USMIMG;
    }

    public static void setUSMIMG(JLabel USMIMG) {
        Interfaz.USMIMG = USMIMG;
    }

    public static JLabel getPuntosUnicosLLDA() {
        return PuntosUnicosLLDA;
    }

    public static void setPuntosUnicosLLDA(JLabel puntosUnicosLLDA) {
        Interfaz.PuntosUnicosLLDA = puntosUnicosLLDA;
    }

    public static JLabel getPuntosUnicosUSM() {
        return PuntosUnicosUSM;
    }

    public static void setPuntosUnicosUSM(JLabel puntosUnicosUSM) {
        Interfaz.PuntosUnicosUSM = puntosUnicosUSM;
    }

    public static JLabel getNombreLLDA() {
        return nombreLLDA;
    }

    public static void setNombreLLDA(JLabel nombreLLDA) {
        Interfaz.nombreLLDA = nombreLLDA;
    }

    public static JLabel getNombreUSM() {
        return nombreUSM;
    }

    public static void setNombreUSM(JLabel nombreUSM) {
        Interfaz.nombreUSM = nombreUSM;
    }

    public static JLabel getColasLLDA1() {
        return ColasLLDA1;
    }

    public static void setColasLLDA1(JLabel ColasLLDA) {
        Interfaz.ColasLLDA1 = ColasLLDA;
    }

    public static JLabel getColasUSM1() {
        return ColasUSM1;
    }

    public static void setColasUSM1(JLabel ColasUSM) {
        Interfaz.ColasUSM1 = ColasUSM;
    }

    public static JLabel getColasLLDA2() {
        return ColasLLDA2;
    }

    public static void setColasLLDA2(JLabel ColasLLDA2) {
        Interfaz.ColasLLDA2 = ColasLLDA2;
    }

    public static JLabel getColasLLDA3() {
        return ColasLLDA3;
    }

    public static void setColasLLDA3(JLabel ColasLLDA3) {
        Interfaz.ColasLLDA3 = ColasLLDA3;
    }

    public static JLabel getColasLLDA4() {
        return ColasLLDA4;
    }

    public static void setColasLLDA4(JLabel ColasLLDA4) {
        Interfaz.ColasLLDA4 = ColasLLDA4;
    }

    public static JLabel getColasUSM2() {
        return ColasUSM2;
    }

    public static void setColasUSM2(JLabel ColasUSM2) {
        Interfaz.ColasUSM2 = ColasUSM2;
    }

    public static JLabel getColasUSM3() {
        return ColasUSM3;
    }

    public static void setColasUSM3(JLabel ColasUSM3) {
        Interfaz.ColasUSM3 = ColasUSM3;
    }

    public static JLabel getColasUSM4() {
        return ColasUSM4;
    }

    public static void setColasUSM4(JLabel ColasUSM4) {
        Interfaz.ColasUSM4 = ColasUSM4;
    }
    
    public static void agregarGanador(String elemento) {
        modeloListaGanadores.addElement(elemento);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Colas;
    private javax.swing.JPanel Colas2;
    public static javax.swing.JLabel ColasLLDA1;
    public static javax.swing.JLabel ColasLLDA2;
    public static javax.swing.JLabel ColasLLDA3;
    public static javax.swing.JLabel ColasLLDA4;
    public static javax.swing.JLabel ColasUSM1;
    public static javax.swing.JLabel ColasUSM2;
    public static javax.swing.JLabel ColasUSM3;
    public static javax.swing.JLabel ColasUSM4;
    public static javax.swing.JLabel EstadoIA;
    private javax.swing.JLabel LLDAFondo;
    public static javax.swing.JLabel LLDAIMG;
    public static javax.swing.JList<String> ListaGanadores;
    public static javax.swing.JLabel PuntosLLDA1;
    public static javax.swing.JLabel PuntosUSM1;
    public static javax.swing.JLabel PuntosUnicosLLDA;
    public static javax.swing.JLabel PuntosUnicosUSM;
    private javax.swing.JSlider SliderAITimer;
    private javax.swing.JLabel USMFondo;
    public static javax.swing.JLabel USMIMG;
    public static javax.swing.JLabel cancelLabel;
    public static javax.swing.JLabel coronaLabelLLDA;
    public static javax.swing.JLabel coronaLabelUSM;
    public static javax.swing.JLabel empateLabel;
    public static javax.swing.JLabel ganadoresLLDA;
    public static javax.swing.JLabel ganadoresUSM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public static javax.swing.JLabel nombreLLDA;
    public static javax.swing.JLabel nombreUSM;
    // End of variables declaration//GEN-END:variables
}
